# Generated by Django 3.2 on 2021-05-07 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_post_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='due_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='due_date',
            field=models.DateField(),
        ),
    ]
