# Generated by Django 3.2 on 2021-05-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='choice',
            field=models.CharField(choices=[('movie', 'movie'), ('drama', 'drama'), ('programming', 'programming')], default='drama', max_length=11),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='max 200', max_length=200),
        ),
    ]
