# Generated by Django 3.2 on 2021-05-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_auto_20210503_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='choice',
            field=models.CharField(choices=[('movie', 'movie'), ('drama', 'drama'), ('programming', 'programming')], default='drama', max_length=11),
        ),
    ]
