# Generated by Django 3.2.3 on 2021-05-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
