# Generated by Django 3.2 on 2021-05-07 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_schedule_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='due_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
