# Generated by Django 3.2 on 2021-05-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210508_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='due_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='due_time',
            field=models.TimeField(blank=True),
        ),
    ]
