# Generated by Django 3.2 on 2021-05-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210508_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='due_time',
        ),
        migrations.AlterField(
            model_name='post',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
